create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  game text not null check (game in ('glyph-serpent', 'space-invaders', 'dino-run')),
  name text not null check (name ~ '^[A-Za-z0-9]{1,5}$'),
  score integer not null check (score >= 0 and score <= 10000000),
  level integer not null default 1 check (level between 1 and 100000),
  created_at timestamptz not null default now()
);

create index if not exists game_scores_rank_idx
  on public.game_scores (game, score desc, level desc, created_at asc);
